// Mock database of cities
const cities = [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Houston, TX",
    "Phoenix, AZ",
    "Philadelphia, PA",
    "San Antonio, TX",
    "San Diego, CA",
    "Dallas, TX",
    "San Jose, CA",
    "Austin, TX",
    "Jacksonville, FL",
    "Fort Worth, TX",
    "Columbus, OH",
    "Charlotte, NC",
    "San Francisco, CA",
    "Indianapolis, IN",
    "Seattle, WA",
    "Denver, CO",
    "Washington, DC",
    "Boston, MA",
    "El Paso, TX",
    "Nashville, TN",
    "Detroit, MI",
    "Oklahoma City, OK",
    "Portland, OR",
    "Las Vegas, NV",
    "Memphis, TN",
    "Louisville, KY",
    "Baltimore, MD",
    "Milwaukee, WI",
    "Albuquerque, NM",
    "Tucson, AZ",
    "Fresno, CA",
    "Mesa, AZ",
    "Sacramento, CA",
    "Atlanta, GA",
    "Kansas City, MO",
    "Colorado Springs, CO",
    "Miami, FL",
    "Raleigh, NC",
    "Omaha, NE",
    "Long Beach, CA",
    "Virginia Beach, VA",
    "Oakland, CA",
    "Minneapolis, MN",
    "Tulsa, OK",
    "Arlington, TX",
    "Tampa, FL",
    "New Orleans, LA",
    "Wichita, KS",
    "Cleveland, OH",
    "Bakersfield, CA",
    "Aurora, CO",
    "Anaheim, CA",
    "Honolulu, HI",
    "Santa Ana, CA",
    "Riverside, CA",
    "Corpus Christi, TX",
    "Lexington, KY",
    "Henderson, NV",
    "Stockton, CA",
    "Saint Paul, MN",
    "Cincinnati, OH",
    "St. Louis, MO",
    "Pittsburgh, PA",
    "Greensboro, NC",
    "Lincoln, NE",
    "Anchorage, AK",
    "Plano, TX",
    "Orlando, FL",
    "Irvine, CA",
    "Newark, NJ",
    "Durham, NC",
    "Chula Vista, CA",
    "Toledo, OH",
    "Fort Wayne, IN",
    "St. Petersburg, FL",
    "Laredo, TX",
    "Jersey City, NJ",
    "Chandler, AZ",
    "Madison, WI",
    "Lubbock, TX",
    "Scottsdale, AZ",
    "Reno, NV",
    "Buffalo, NY",
    "Gilbert, AZ",
    "Glendale, AZ",
    "North Las Vegas, NV",
    "Winston-Salem, NC",
    "Chesapeake, VA",
    "Norfolk, VA",
    "Fremont, CA",
    "Garland, TX",
    "Irving, TX",
    "Hialeah, FL",
    "Boise, ID",
    "Bowling Green, KY",
    "Bozeman, MT",
    "Bonita Springs, FL",
    "Bodega Bay, CA",
    // Indian Cities
    "Mumbai, Maharashtra",
    "Delhi, Delhi",
    "Bangalore, Karnataka",
    "Hyderabad, Telangana",
    "Ahmedabad, Gujarat",
    "Chennai, Tamil Nadu",
    "Kolkata, West Bengal",
    "Surat, Gujarat",
    "Pune, Maharashtra",
    "Jaipur, Rajasthan",
    "Lucknow, Uttar Pradesh",
    "Kanpur, Uttar Pradesh",
    "Nagpur, Maharashtra",
    "Indore, Madhya Pradesh",
    "Thane, Maharashtra",
    "Bhopal, Madhya Pradesh",
    "Visakhapatnam, Andhra Pradesh",
    "Pimpri-Chinchwad, Maharashtra",
    "Patna, Bihar",
    "Vadodara, Gujarat",
    "Ghaziabad, Uttar Pradesh",
    "Ludhiana, Punjab",
    "Agra, Uttar Pradesh",
    "Nashik, Maharashtra",
    "Faridabad, Haryana",
    "Meerut, Uttar Pradesh",
    "Rajkot, Gujarat",
    "Kalyan-Dombivli, Maharashtra",
    "Vasai-Virar, Maharashtra",
    "Varanasi, Uttar Pradesh",
    "Srinagar, Jammu and Kashmir",
    "Aurangabad, Maharashtra",
    "Dhanbad, Jharkhand",
    "Amritsar, Punjab",
    "Navi Mumbai, Maharashtra",
    "Allahabad, Uttar Pradesh",
    "Howrah, West Bengal",
    "Ranchi, Jharkhand",
    "Gwalior, Madhya Pradesh",
    "Jabalpur, Madhya Pradesh",
    "Coimbatore, Tamil Nadu",
    "Vijayawada, Andhra Pradesh",
    "Jodhpur, Rajasthan",
    "Madurai, Tamil Nadu",
    "Raipur, Chhattisgarh",
    "Kota, Rajasthan",
    "Guwahati, Assam",
    "Chandigarh, Chandigarh",
    "Solapur, Maharashtra",
    "Hubballi-Dharwad, Karnataka",
    "Trivandrum, Kerala",
    "Kochi, Kerala",
    "Kozhikode, Kerala",
    "Thrissur, Kerala",
    "Kannur, Kerala"
];

// @desc    Search cities
// @route   GET /api/utils/cities?query=xyz
// @access  Public
const searchCities = async (req, res) => {
    const { query } = req.query;

    if (!query) {
        return res.status(200).json([]);
    }

    const filteredCities = cities.filter(city =>
        city.toLowerCase().startsWith(query.toLowerCase())
    );

    // Limit results to top 10 to simulate real API behavior
    res.status(200).json(filteredCities.slice(0, 10));
};

module.exports = {
    searchCities
};
